export { imageProps, default as NImage } from './src/Image'
export type { ImageProps, ImageSlots } from './src/Image'
export { imageGroupProps, default as NImageGroup } from './src/ImageGroup'
export type { ImageGroupProps } from './src/ImageGroup'
export type { ImageInst } from './src/interface'
export type * from './src/public-types'
