export default {
  tabFontSizeSmall: '14px',
  tabFontSizeMedium: '14px',
  tabFontSizeLarge: '16px',
  tabGapSmallLine: '36px',
  tabGapMediumLine: '36px',
  tabGapLargeLine: '36px',
  tabPaddingSmallLine: '6px 0',
  tabPaddingMediumLine: '10px 0',
  tabPaddingLargeLine: '14px 0',
  verticalTabPaddingSmallLine: '0 6px',
  verticalTabPaddingMediumLine: '0 10px',
  verticalTabPaddingLargeLine: '0 14px',
  tabGapSmallBar: '36px',
  tabGapMediumBar: '36px',
  tabGapLargeBar: '36px',
  tabPaddingSmallBar: '4px 0',
  tabPaddingMediumBar: '6px 0',
  tabPaddingLargeBar: '10px 0',
  verticalTabPaddingSmallBar: '0 4px',
  verticalTabPaddingMediumBar: '0 6px ',
  verticalTabPaddingLargeBar: '0 10px ',
  tabGapSmallCard: '4px',
  tabGapMediumCard: '4px',
  tabGapLargeCard: '4px',
  tabPaddingSmallCard: '6px 10px',
  tabPaddingMediumCard: '8px 12px',
  tabPaddingLargeCard: '8px 16px',
  tabPaddingSmallSegment: '4px 0',
  tabPaddingMediumSegment: '6px 0',
  tabPaddingLargeSegment: '8px 0',
  verticalTabPaddingLargeSegment: '0 8px',
  verticalTabPaddingSmallCard: '10px 6px',
  verticalTabPaddingMediumCard: '12px 8px',
  verticalTabPaddingLargeCard: '16px 8px',
  verticalTabPaddingSmallSegment: '0 4px',
  verticalTabPaddingMediumSegment: '0 6px',
  tabGapSmallSegment: '0',
  tabGapMediumSegment: '0',
  tabGapLargeSegment: '0',
  panePaddingSmall: '8px 0 0 0',
  panePaddingMedium: '12px 0 0 0',
  panePaddingLarge: '16px 0 0 0',
  closeSize: '18px',
  closeIconSize: '14px'
}
