export { NH1, NH2, NH3, NH4, NH5, NH6 } from './src/headers'
export type { HeaderProps as H1Props } from './src/create-header'
export type { HeaderProps as H2Props } from './src/create-header'
export type { HeaderProps as H3Props } from './src/create-header'
export type { HeaderProps as H4Props } from './src/create-header'
export type { HeaderProps as H5Props } from './src/create-header'
export type { HeaderProps as H6Props } from './src/create-header'
export { default as NA } from './src/a'
export type { AProps } from './src/a'
export { default as NP } from './src/p'
export type { PProps } from './src/p'
export { default as NBlockquote } from './src/blockquote'
export type { BlockquoteProps } from './src/blockquote'
export { default as NHr } from './src/hr'
export { default as NUl } from './src/ul'
export type { UlProps } from './src/ul'
export { default as NOl } from './src/ol'
export type { OlProps } from './src/ol'
export { default as NLi } from './src/li'
export { default as NText } from './src/text'
export type { TextProps } from './src/text'
