export { NH1, NH2, NH3, NH4, NH5, NH6 } from './src/headers.js'
export { default as A } from './src/a.vue'
export { default as P } from './src/p.vue'
export { default as NBlockquote } from './src/blockquote.vue'
export { default as NHr } from './src/hr.vue'
export { default as NUl } from './src/ul.vue'
export { default as NOl } from './src/ol.vue'
export { default as NLi } from './src/li.vue'
export { default as NText } from './src/text.vue'
export * from './styles'
