export default {
  padding: '4px 0',
  optionHeightSmall: '28px',
  optionHeightMedium: '34px',
  optionHeightLarge: '40px',
  optionHeightHuge: '46px',
  optionSuffixWidthSmall: '28px',
  optionSuffixWidthMedium: '28px',
  optionSuffixWidthLarge: '32px',
  optionSuffixWidthHuge: '32px',
  optionIconSuffixWidthSmall: '40px',
  optionIconSuffixWidthMedium: '40px',
  optionIconSuffixWidthLarge: '44px',
  optionIconSuffixWidthHuge: '44px',
  optionPrefixWidthSmall: '28px',
  optionPrefixWidthMedium: '28px',
  optionPrefixWidthLarge: '32px',
  optionPrefixWidthHuge: '32px',
  optionIconPrefixWidthSmall: '44px',
  optionIconPrefixWidthMedium: '44px',
  optionIconPrefixWidthLarge: '48px',
  optionIconPrefixWidthHuge: '48px'
}
