export type { TabsInst } from './src/interface'
export { default as NTab, tabProps } from './src/Tab'
export type { TabProps } from './src/Tab'
export { default as NTabPane, tabPaneProps } from './src/TabPane'
export type { TabPaneProps, TabPaneSlots } from './src/TabPane'
export { default as NTabs, tabsProps } from './src/Tabs'
export type { TabsProps, TabsSlots } from './src/Tabs'
