export { default as NTabs, tabsProps } from './src/Tabs'
export type { TabsProps } from './src/Tabs'
export { default as NTabPane, tabPaneProps } from './src/TabPane'
export type { TabPaneProps } from './src/TabPane'
export { default as NTab, tabProps } from './src/Tab'
export type { TabProps } from './src/Tab'
export type { TabsInst } from './src/interface'
