export { default as NUpload } from './src/Upload'
export { default as NUploadDragger } from './src/UploadDragger'
export type { UploadProps } from './src/Upload'
export type { uploadDraggerKey } from './src/UploadDragger'
export type { UploadInst } from './src/interface'
