export { default as NTable, tableProps } from './src/Table'
export type { TableProps } from './src/Table'
export { default as NTbody } from './src/Tbody'
export { default as NTd } from './src/Td'
export { default as NTh } from './src/Th'
export { default as NThead } from './src/Thead'
export { default as NTr } from './src/Tr'
