export { default as NHeatmap } from './src/Heatmap'
export { heatmapProps } from './src/Heatmap'
export type { HeatmapProps } from './src/Heatmap'
export type * from './src/public-types'
export { heatmapMockData } from './src/utils'
export * from './styles'
