import type { GlobalThemeOverrides } from '../../../../config-provider'

export const elementPlusLightOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#409EFF',
    primaryColorHover: '#66B1FF',
    primaryColorPressed: '#337ECC',
    primaryColorSuppl: '#66B1FF',
    infoColor: '#909399',
    infoColorHover: '#A6A9AD',
    infoColorPressed: '#73767A',
    infoColorSuppl: '#A6A9AD',
    successColor: '#67C23A',
    successColorHover: '#85CE61',
    successColorPressed: '#529B2E',
    successColorSuppl: '#85CE61',
    warningColor: '#E6A23C',
    warningColorHover: '#EBB563',
    warningColorPressed: '#B88230',
    warningColorSuppl: '#EBB563',
    errorColor: '#F56C6C',
    errorColorHover: '#F89898',
    errorColorPressed: '#C45656',
    errorColorSuppl: '#F89898',
    textColor1: '#303133',
    textColor2: '#606266',
    textColor3: '#909399',
    textColorDisabled: '#C0C4CC',
    placeholderColor: '#A8ABB2',
    borderColor: '#DCDFE6',
    dividerColor: '#E4E7ED',
    borderRadius: '4px',
    borderRadiusSmall: '2px',
    bodyColor: '#FFFFFF',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    tableColor: '#FFFFFF',
    tableHeaderColor: '#FAFAFA',
    inputColor: '#FFFFFF',
    actionColor: '#F5F7FA',
    tagColor: '#ECF5FF',
    hoverColor: '#F5F7FA',
    pressedColor: '#E6E8EB',
    fontSize: '14px',
    fontFamily:
      '"Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif',
    boxShadow1: '0 2px 4px rgba(0, 0, 0, 0.04), 0 0 6px rgba(0, 0, 0, 0.04)',
    boxShadow2: '0 4px 12px rgba(0, 0, 0, 0.08), 0 0 6px rgba(0, 0, 0, 0.04)',
    boxShadow3: '0 8px 24px rgba(0, 0, 0, 0.12), 0 0 8px rgba(0, 0, 0, 0.06)'
  }
}
