export default {
  blankHeightSmall: '28px',
  blankHeightMedium: '34px',
  blankHeightLarge: '40px',
  feedbackPadding: '3px 0 0 2px',
  feedbackHeightSmall: '21px',
  feedbackHeightMedium: '21px',
  feedbackHeightLarge: '24px',
  feedbackFontSizeSmall: '13px',
  feedbackFontSizeMedium: '13px',
  feedbackFontSizeLarge: '14px',
  labelFontSizeLeftSmall: '14px',
  labelFontSizeLeftMedium: '14px',
  labelFontSizeLeftLarge: '15px',
  labelFontSizeTopSmall: '13px',
  labelFontSizeTopMedium: '13px',
  labelFontSizeTopLarge: '14px',
  labelHeightSmall: '21px',
  labelHeightMedium: '21px',
  labelHeightLarge: '24px',
  labelPaddingVertical: '0 0 3px 2px',
  labelPaddingHorizontal: '0 12px 0 0',
  labelTextAlignVertical: 'left',
  labelTextAlignHorizontal: 'right'
}
