export default {
  blankHeightSmall: '28px',
  blankHeightMedium: '34px',
  blankHeightLarge: '40px',
  feedbackFontSizeSmall: '13px',
  feedbackFontSizeMedium: '13px',
  feedbackFontSizeLarge: '14px',
  labelFontSizeLeftSmall: '14px',
  labelFontSizeLeftMedium: '14px',
  labelFontSizeLeftLarge: '15px',
  labelFontSizeTopSmall: '13px',
  labelFontSizeTopMedium: '13px',
  labelFontSizeTopLarge: '14px',
  labelHeightSmall: '18px',
  labelHeightMedium: '18px',
  labelHeightLarge: '20px',
  labelPaddingVertical: '0 0 8px 2px',
  labelPaddingHorizontal: '0 12px 0 0',
  labelTextAlignHorizontal: 'right'
}
