name: Issue Reply

on:
  issues:
    types: [labeled]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Usage
        if: github.event.label.name == 'Usage' || github.event.label.name == 'Question'
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}, we use GitHub issues to trace bugs or discuss plans of Naive UI. So, please don't ask usage questions. You can join the community to ask questions:
            - [Discord](https://discord.gg/Pqv7Mev5Dd)
            - DingTalk Group 1 (Member limit reached) 33482509
            - DingTalk Group 2 (Member limit reached) 35886835
            - DingTalk Group 3 (Member limit reached) 32377370
            - DingTalk Group 4 (Member limit reached) 8165002788
            - DingTalk Group 5 31205022250

            你好 @${{ github.event.issue.user.login }}，Naive UI Issue 板块是用于 bug 反馈与需求讨论的地方，请勿询问如何使用的问题。你可以加入社区进行提问：
            - [Discord](https://discord.gg/Pqv7Mev5Dd)
            - 钉钉一群 33482509 (已满)
            - 钉钉二群 35886835 (已满)
            - 钉钉三群 32377370 (已满)
            - 钉钉四群 8165002788 (已满)
            - 钉钉五群 31205022250
